package BersaniChiappiniFraschini.CKBApplicationServer.notification;

public enum NotificationType {
    NEW_TOURNAMENT,
    NEW_BATTLE,
    NEW_INVITE,
    INVITE_STATUS_UPDATE,
    NEW_REPOSITORY_INVITE,
    GROUP_REMOVED_FROM_BATTLE,
    NEW_RANK_AVAILABLE,
    SUCCESSFUL_BATTLE_ENROLLMENT,
    SUCCESSFUL_TOURNAMENT_SUBSCRIPTION,
    MANUAL_EVALUATION_REQUIRED
}
