version: '3.1'

services:
  server:
    build:
      context: ./server
    ports:
      - "8081:8081"

    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

    depends_on:
      - db

  db:
    image: mysql

    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql

    command: [ "--init-file", "/docker-entrypoint-initdb.d/init.sql" ]